### ISSUE TITLE
GT Transcript Put Object Broken

### ISSUE THREAD

**Issue by seandenigris** [seandenigris/Pharo-Enhancements#29]
I tried this, but nothing happens on click:
```smalltalk
clickAttr := BrTextClickAttribute new 
        beNotOverwritableByStyler;
        action: [ :aText :aTarget :aTextEditor :anEvent | 
            anEvent target phlow spawnObject: anObject ];
        yourself.
        
GtTranscript default next
        attribute: clickAttr;
        putAll: 'this';
        cr.
```

2022-10-12 - [Asked on Discord](https://discord.com/channels/729445214812504107/755319168504692778/1029798443826294835)

**Comment by seandenigris** [comment]
Pending https://github.com/feenkcom/gtoolkit/issues/2834

**Comment by refactoringdr** [comment]
Pushed a fix.

**Comment by seandenigris** [comment]
Looks like the patch was reverted. I missed my chance lol ;-)

**Comment by refactoringdr** [comment]
If you want a temporary workaround: `BrTextEditorModel dontUseParagraphEditor: true` will revert to using the older (slower) word-based editor. But your click attribute will work again. Hoping to have a real fix out next week.

**Comment by seandenigris** [comment]
I can wait for a proper fix. Thanks for the support :)

**Comment by refactoringdr** [comment]
Just pushed a different fix for this. Give it a spin!

**Comment by seandenigris** [comment]
https://user-images.githubusercontent.com/184176/197607707-540c6d32-e638-43a2-b64b-c1ad0d8bbfe2.mov
