### ISSUE TITLE
[CI]: Main project in Iceberg?

### ISSUE THREAD

**Issue by snrnyc** [seandenigris/Pharo-Enhancements#41]
Right now, it seems that smalltalkCI loads the main project from a local repo. The drawback of this is that further development on the CI image artifact requires cloning the repo first.

**Comment by seandenigris** [comment]
Smalltalk CI has a setting to register it in Iceberg [per the docs](https://github.com/hpi-swa/smalltalkCI#scimetacelloloadspec): `#registerInIceberg : true`, but you have to change the checkout to fetch all commits [per the docs](https://github.com/hpi-swa/setup-smalltalkCI?tab=readme-ov-file#pharos-specific-registering-repository-in-iceberg). Changed the PE's reusable workflow to do so, but its CI is getting a weird error preventing a successful build artifact ([reported on Pharo Discord](https://discord.com/channels/223421264751099906/223421264751099906/1281057325146443868))

**Comment by seandenigris** [comment]
Okay, verified in [latest Resources-Live CI job](https://github.com/seandenigris/Resources-Live/actions/runs/10712079693/job/29702283683) that in the built image, Iceberg has the tested project's repository. It just doesn't have the local clone in the expected folder, so you have to "Repair repository" and clone again
